[2023-10-22 06:27:10,569] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rate_to_postgres.get_rate_from_api manual__2023-10-22T06:26:41.517249+00:00 [queued]>
[2023-10-22 06:27:10,582] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rate_to_postgres.get_rate_from_api manual__2023-10-22T06:26:41.517249+00:00 [queued]>
[2023-10-22 06:27:10,583] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-22 06:27:10,585] {taskinstance.py:1377} INFO - Starting attempt 5 of 6
[2023-10-22 06:27:10,586] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-22 06:27:10,603] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_rate_from_api> on 2023-10-22 06:26:41.517249+00:00
[2023-10-22 06:27:10,612] {standard_task_runner.py:52} INFO - Started process 4070 to run task
[2023-10-22 06:27:10,617] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_to_postgres', 'get_rate_from_api', 'manual__2023-10-22T06:26:41.517249+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/get_exchange_rate.py', '--cfg-path', '/tmp/tmp31illjua', '--error-file', '/tmp/tmp691z5ixf']
[2023-10-22 06:27:10,618] {standard_task_runner.py:80} INFO - Job 19: Subtask get_rate_from_api
[2023-10-22 06:27:10,720] {task_command.py:371} INFO - Running <TaskInstance: exchange_rate_to_postgres.get_rate_from_api manual__2023-10-22T06:26:41.517249+00:00 [running]> on host 7fbc45d826e5
[2023-10-22 06:27:10,826] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=andrey
AIRFLOW_CTX_DAG_ID=exchange_rate_to_postgres
AIRFLOW_CTX_TASK_ID=get_rate_from_api
AIRFLOW_CTX_EXECUTION_DATE=2023-10-22T06:26:41.517249+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-22T06:26:41.517249+00:00
[2023-10-22 06:27:11,688] {logging_mixin.py:115} INFO - ######### datetime_rate:  1697956023
[2023-10-22 06:27:11,689] {logging_mixin.py:115} INFO - ########## value_rate:  2875406.58516
[2023-10-22 06:27:11,708] {base.py:68} INFO - Using connection ID 'conn_exchange_rate' for task execution.
[2023-10-22 06:27:11,731] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_exchange_rate.py", line 35, in get_exchange_rate
    VALUES (to_timestamp({datetime_rate}), {SOURCE}, {CURRENCIES}, {value_rate})""")
psycopg2.errors.UndefinedColumn: column "btc" does not exist
LINE 2: ...                VALUES (to_timestamp(1697956023), BTC, RUB, ...
                                                             ^

[2023-10-22 06:27:11,748] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rate_to_***, task_id=get_rate_from_api, execution_date=20231022T062641, start_date=20231022T062710, end_date=20231022T062711
[2023-10-22 06:27:11,764] {standard_task_runner.py:97} ERROR - Failed to execute job 19 for task get_rate_from_api (column "btc" does not exist
LINE 2: ...                VALUES (to_timestamp(1697956023), BTC, RUB, ...
                                                             ^
; 4070)
[2023-10-22 06:27:11,801] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-22 06:27:11,878] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
